### ISSUE TITLE
Req: sortvar move jpg also

### ISSUE THREAD

**Issue by cdeschenes** [vaminator/vamtb#1]
I am loving this utility! Thanks for all your work on this, as it has saved me TONS of time. I was wondering if there is a way to add moving JPG & TXT files that have the same name as the VAR file. This way all preview images and dependency lists will be moved in folders with the VARs.

**Comment by cdeschenes** [comment]
Figured it out

def sort_vars(ctx):
    """Moves vars to subdirectory named by its creator"""
    dir=ctx.obj['dir']
    logging.info("Sorting var in %s" % dir)
    **vars_files = vamdirs.list_vars(dir, pattern="*")**
    for var_file in vars_files:
        varfile.split_varname(var_file, dest_dir = "%s/AddonPackages" % dir)

**Comment by vaminator** [comment]
Thanks for the message !

Good idea. I made it a bit more strict, otherwise we will be moving also files which are neither var nor jpg.
Now sortvar will only move var which have a correct name, that have a meta.json which is correct json and if it has a jpg named the same it will also be moved.

Hope it solves your use case. If not, feel free to reopen.
